%% EXPORT T-MAPS AND Z-MAPS
% This script locates the existing T-maps (generated by the SPM models),
% copies them to your Results folder, and calculates corresponding Z-maps.
%
% INPUTS:
% - Source: ./example_data/pet_subjects\<Group>\<Subject>Contrast\spmT_0001.nii
% - SPM.mat: Needed for degrees of freedom (df)
%
% OUTPUTS:
% - ./outputs/results\<Subject>\Tmap.nii
% - ./outputs/results\<Subject>\Zmap.nii

clear; clc;
script_dir = fileparts(mfilename('fullpath'));
addpath(script_dir);
spm('Defaults', 'PET');

%% ==== CONFIGURATION ====
% List all groups you want to process
cfg = ssa.default_config();
groups_to_process = {'AD', 'MCI'};
source_root = cfg.root_dir;
output_root = cfg.results_root;

%% ==== MAIN PROCESSING LOOP ====
for g = 1:length(groups_to_process)
    grpName = groups_to_process{g};
    grpPath = fullfile(source_root, grpName);
    
    fprintf('\n=== Processing Group: %s ===\n', grpName);
    
    % Find subjects
    subj_dirs = dir(grpPath);
    subj_dirs = subj_dirs([subj_dirs.isdir] & ~startsWith({subj_dirs.name}, '.'));
    
    for i = 1:length(subj_dirs)
        subjID = subj_dirs(i).name;
        
        % Skip Contrast folders appearing as subjects
        if contains(subjID, 'Contrast'), continue; end
        
        % Locate Contrast Folder
        contrastPath = fullfile(grpPath, [subjID 'Contrast']);
        if ~exist(contrastPath, 'dir')
            % Fallback search
            candidates = dir(fullfile(grpPath, [subjID '*Contrast*']));
            if ~isempty(candidates)
                contrastPath = fullfile(grpPath, candidates(1).name);
            else
                continue; % No contrast folder, skip
            end
        end
        
        % Locate SPM.mat and T-map
        spmFile = fullfile(contrastPath, 'SPM.mat');
        tmapFile = fullfile(contrastPath, 'spmT_0001.nii'); % Contrast 1 (Hypometabolism)
        
        if ~exist(spmFile, 'file') || ~exist(tmapFile, 'file')
            fprintf('  [SKIP] %s: Missing SPM.mat or spmT_0001.nii\n', subjID);
            continue;
        end
        
        % Define Output Directory
        subjOutDir = fullfile(output_root, subjID);
        if ~exist(subjOutDir, 'dir'), mkdir(subjOutDir); end
        
        fprintf('  Processing %s...\n', subjID);
        
        try
            % 1. COPY T-MAP
            copyfile(tmapFile, fullfile(subjOutDir, 'Tmap.nii'));
            
            % 2. CREATE Z-MAP
            % Load SPM to get Degrees of Freedom
            load(spmFile, 'SPM');
            df = SPM.xX.erdf;
            
            % Load T-map Data
            V_t = spm_vol(tmapFile);
            T_data = spm_read_vols(V_t);
            
            % Convert T to Z
            % Z = inverseNormal( StudentT_CDF( T, df ) )
            % Using SPM functions to handle nans/infinity safely
            P_val = spm_Tcdf(T_data, df);
            Z_data = spm_invNcdf(P_val);
            
            % Mask out background (where T was NaN or 0)
            Z_data(isnan(T_data) | T_data == 0) = NaN;
            
            % Cap extreme values if necessary (avoid Inf)
            Z_data(isinf(Z_data)) = sign(Z_data(isinf(Z_data))) * 10; % Cap at Z=10
            
            % Write Z-map
            V_z = V_t;
            V_z.fname = fullfile(subjOutDir, 'Zmap.nii');
            V_z.descrip = sprintf('Z-map calculated from T-map (df=%.2f)', df);
            spm_write_vol(V_z, Z_data);
            
            fprintf('    => Created Tmap.nii and Zmap.nii\n');
            
        catch ME
            fprintf('    => ERROR: %s\n', ME.message);
        end
    end
end

fprintf('\n=== ALL DONE ===\n');
